# Author: Rothang Ralph Ralefaso
# Location: /media/unusualralph/linus/ATI/Makefile

BUILD_DIR = build
EXE = ati_app

# Default target (runs when you just type 'make')
all: build

# Compiles the project
build:
	@mkdir -p $(BUILD_DIR)
	@cd $(BUILD_DIR) && cmake .. && make

# THE RUN TARGET: This starts the program
run: build
	@echo "Launching $(EXE)..."
	@./$(BUILD_DIR)/$(EXE)

# Cleans up build artifacts
clean:
	@rm -rf $(BUILD_DIR)
	@echo "Build directory removed."

.PHONY: all build run clean