# Author: Rothang Ralph Ralefaso
# Simple wrapper for CMake build process

BUILD_DIR = build

all: setup build

setup:
	@mkdir -p $(BUILD_DIR)

build:
	@cd $(BUILD_DIR) && cmake .. && make

run:
	@./$(BUILD_DIR)/ati_app

clean:
	@rm -rf $(BUILD_DIR)
	@echo "Build directory cleaned."

.PHONY: all setup build run clean